name: Go version action
description: A GitHub Action providing the latest Go version, your projects minimum Go version, and a build matrix to your workflow
branding:
  icon: box
  color: blue
inputs:
  working-directory:
    description: Working direcory
    required: false
    default: .
outputs:
  latest:
    description: The latest go version
  minimal:
    description: The minial go version (as specified by go.mod)
  matrix:
    description: An (stringified) array of go versions from the minimal supported version to the latest released version
  module:
    description: The go module path (as specified by go.mod)
runs:
  using: node16
  main: dist/index.js
