name: Build and test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build ChangeLog
        run: npx conventional-changelog-cli
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run build
      - run: |
          npm run package
      - uses: ./
        id: go-version
        with:
          working-directory: ./__tests__/testdata
      - run: |
          test '${{ steps.go-version.outputs.module }}' == 'example.com/go/testmodule'
      - run: |
          test '${{ steps.go-version.outputs.minimal }}' == '1.13'
      - run: |
          test '${{ steps.go-version.outputs.latest }}' == '1.18'
      - run: |
          test '${{ steps.go-version.outputs.matrix }}' == '["1.13","1.14","1.15","1.16","1.17","1.18"]'
