name: 'build-test-release'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: go-version
        with:
          working-directory: ./__tests__/testdata
      - run: |
          test '${{ steps.go-version.outputs.module }}' == 'example.com/go/testmodule'
      - run: |
          test '${{ steps.go-version.outputs.minimal }}' == '1.13'
      - run: |
          test '${{ steps.go-version.outputs.latest }}' == '1.16'
      - run: |
          test '${{ steps.go-version.outputs.matrix }}' == '["1.16","1.15","1.14","1.13"]'
  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run build
          npm run package
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/index.js
          git commit -m "Publish dist" || echo "Nothing to commit"
          git push origin main
          git tag --force v1
          git push origin v1 --force
